import countyCommissionDistricts from "@/demo-data/miami-dade-county-commission-districts.json";
import districtBoundary from "@/demo-data/district-7-boundary.json";
import municipalities from "@/demo-data/miami-dade-municipalities.json";

export const DEMO_JURISDICTION_SEED = {
  districtBoundaryName:
    "Miami-Dade County Commission District 7 (official ArcGIS boundary)",
  districtBoundaryGeoJson: JSON.stringify(districtBoundary),
  municipalityBoundaryName:
    "Miami-Dade County municipalities (official ArcGIS boundary layer)",
  municipalityBoundaryGeoJson: JSON.stringify(municipalities),
  countyCommissionDistrictsName:
    "Miami-Dade County commission districts (official ArcGIS boundary layer)",
  countyCommissionDistrictsGeoJson: JSON.stringify(countyCommissionDistricts),
  districtMatchKeywords: "",
  districtOutsideKeywords: "",
  stateKeywords: "",
  countyKeywords: "",
  utilityKeywords: "",
  privatePropertyKeywords: "",
  schoolKeywords: "",
  transitKeywords: "",
  parksKeywords: "",
} as const;

export const DEMO_STAFF_MEMBERS = [
  {
    id: "staff-alejandro-servalli",
    name: "Alejandro Servalli",
    email: "Alejandro.servalli@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Small Business, Elderly, Webinars, General Constituent Issues",
  },
  {
    id: "staff-anthony-escarra",
    name: "Anthony Escarra",
    email: "Anthony.Escarra@miamidade.gov",
    title: "Chief of Staff",
    focusAreas: "All",
  },
  {
    id: "staff-carol-gustafson",
    name: "Carol Gustafson",
    email: "Carol.Gustafson@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Parks, Events, Sponsorship Checks",
  },
  {
    id: "staff-david-garcia",
    name: "David Garcia",
    email: "David.Garcia@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Elderly, Housing, General Constituent Services",
  },
  {
    id: "staff-diego-abreu",
    name: "Diego Abreu",
    email: "diego.abreu@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Roads, Transportation, General Constituent Issues",
  },
  {
    id: "staff-eugene-savitsky",
    name: "Eugene Savitsky",
    email: "Eugene.Savitsky2@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Communications, Event Filming, Post Production, Social Media",
  },
  {
    id: "staff-laura-verdauger",
    name: "Laura Verdauger",
    email: "laura.verdauger@miamidade.gov",
    title: "Deputy Chief of Staff",
    focusAreas: "All",
  },
  {
    id: "staff-pamela-krivenko",
    name: "Pamela Krivenko",
    email: "d7Scheduling@miamidade.gov",
    title: "Commissioners Aide",
    focusAreas: "Scheduling",
  },
  {
    id: "staff-stephanie-womble",
    name: "Stephanie Womble",
    email: "Stephanie.Womble@miamidade.gov",
    title: "Director of Communications",
    focusAreas: "Communications, Event Filming, Post Production, Social Media",
  },
] as const;

export const DEMO_REPORTS = [
  {
    id: "demo-report-sidewalks-miami",
    publicTrackingToken: "f6259554b975af8d86395e06",
    status: "received",
    category: "Sidewalks",
    description: "broken sidewalks",
    addressText: "3636 SW 16th Terrace, Miami, FL 33145",
    latitude: 25.756558761221,
    longitude: -80.253534010134,
    locationSource: "census_geocoder",
    geocodingStatus: "matched",
    geocodedAddress: "3636 SW 16TH TER, MIAMI, FL, 33145",
    geocodingProvider: "census",
    geocodedAt: "2026-05-18T15:10:26.341Z",
    municipalityName: "MIAMI",
    municipalityCode: "01",
    municipalityLookupStatus: "matched",
    municipalitySource: "Miami-Dade County municipalities (official ArcGIS boundary layer)",
    municipalityMatchedAt: "2026-05-18T15:47:04.276Z",
    parcelLookupStatus: "matched",
    parcelFolio: "0141090700020",
    parcelAddress: "3650 SW 16 TER 2",
    parcelOwner: "JUANA HILDA GARCIA",
    rightOfWayHint: "on_parcel",
    parcelMatchedAt: "2026-05-18T15:47:04.276Z",
    residentName: "Diego",
    residentEmail: "d48reu@gmail.com",
    residentPhone: "305.360.9229",
    preferredLanguage: "English",
    contactConsent: true,
    newsletterOptIn: true,
    newsletterOptInAt: "2026-05-18T15:10:26.341Z",
    notificationReviewStatus: "needs_edit",
    notificationReviewNote:
      "Good candidate for a more specific resident-facing sidewalk explanation.",
    notificationReviewedAt: "2026-05-18T15:48:04.276Z",
    assignedStaffId: null,
    createdAt: "2026-05-18T15:10:26.341Z",
    updatedAt: "2026-05-18T15:47:04.276Z",
  },
  {
    id: "demo-report-pothole-miami",
    publicTrackingToken: "1eb6b91f12390d5bf08a9540",
    status: "routed",
    category: "Roads and potholes",
    description: "big pothole at Douglas Road and US1 intersection",
    addressText: "3060 SW 37th Ct, Miami, FL 33146",
    latitude: 25.733896101946,
    longitude: -80.255020746966,
    locationSource: "census_geocoder",
    geocodingStatus: "matched",
    geocodedAddress: "3060 SW 37TH CT, MIAMI, FL, 33134",
    geocodingProvider: "census",
    geocodedAt: "2026-05-18T16:00:37.363Z",
    municipalityName: "MIAMI",
    municipalityCode: "01",
    municipalityLookupStatus: "matched",
    municipalitySource: "Miami-Dade County municipalities (official ArcGIS boundary layer)",
    municipalityMatchedAt: "2026-05-18T16:00:37.848Z",
    parcelLookupStatus: "matched",
    parcelFolio: "0141200680012",
    parcelAddress: null,
    parcelOwner: "MIAMI DADE COUNTY TRANSIT",
    rightOfWayHint: "on_parcel",
    parcelMatchedAt: "2026-05-18T16:00:37.848Z",
    residentName: "Diego",
    residentEmail: "d48reu@gmail.com",
    residentPhone: "305.360.9229",
    preferredLanguage: "English",
    contactConsent: true,
    newsletterOptIn: true,
    newsletterOptInAt: "2026-05-18T16:00:37.848Z",
    notificationReviewStatus: "ready",
    notificationReviewNote: "Ready to send after staff routing review.",
    notificationReviewedAt: "2026-05-18T16:20:37.848Z",
    assignedStaffId: "staff-diego-abreu",
    createdAt: "2026-05-18T16:00:37.848Z",
    updatedAt: "2026-05-18T16:24:30.938Z",
  },
  {
    id: "demo-report-park-lighting",
    publicTrackingToken: "d6fcf1697ab3fa11e12a2d50",
    status: "awaiting_agency",
    category: "Parks",
    description:
      "Several path lights are out near the park entrance and walking loop. Residents say the area feels noticeably less safe after sunset.",
    addressText: "Alice Wainwright Park, Miami, FL 33133",
    latitude: 25.731446,
    longitude: -80.234212,
    locationSource: "none",
    geocodingStatus: "not_attempted",
    geocodedAddress: null,
    geocodingProvider: null,
    geocodedAt: null,
    municipalityName: "MIAMI",
    municipalityCode: "01",
    municipalityLookupStatus: "matched",
    municipalitySource: "Miami-Dade County municipalities (official ArcGIS boundary layer)",
    municipalityMatchedAt: "2026-05-17T14:12:00.000Z",
    parcelLookupStatus: "not_attempted",
    parcelFolio: null,
    parcelAddress: null,
    parcelOwner: null,
    rightOfWayHint: "unclear",
    parcelMatchedAt: null,
    residentName: "Carol Demo",
    residentEmail: "parks-demo@example.com",
    residentPhone: null,
    preferredLanguage: "English",
    contactConsent: true,
    newsletterOptIn: false,
    newsletterOptInAt: null,
    notificationReviewStatus: "hold",
    notificationReviewNote: "Hold until the parks contact confirms the facility owner.",
    notificationReviewedAt: "2026-05-17T14:45:00.000Z",
    assignedStaffId: "staff-carol-gustafson",
    createdAt: "2026-05-17T14:12:00.000Z",
    updatedAt: "2026-05-17T15:05:00.000Z",
  },
  {
    id: "demo-report-outside-district",
    publicTrackingToken: "077ed173c249c95be79ec176",
    status: "received",
    category: "Roads and potholes",
    description:
      "Test example: large pothole reported outside Miami-Dade County District 7 for jurisdiction review.",
    addressText: "100 Washington Ave, Miami Beach, FL 33139",
    latitude: 25.769987784265,
    longitude: -80.135228161278,
    locationSource: "census_geocoder",
    geocodingStatus: "matched",
    geocodedAddress: "100 WASHINGTON AVE, MIAMI BEACH, FL, 33139",
    geocodingProvider: "us_census_geocoder",
    geocodedAt: "2026-05-18T16:31:53.929Z",
    municipalityName: "MIAMI BEACH",
    municipalityCode: null,
    municipalityLookupStatus: "matched",
    municipalitySource: "boundary",
    municipalityMatchedAt: "2026-05-18T16:31:53.929Z",
    parcelLookupStatus: "not_attempted",
    parcelFolio: null,
    parcelAddress: null,
    parcelOwner: null,
    rightOfWayHint: "unclear",
    parcelMatchedAt: null,
    residentName: "Outside District Example",
    residentEmail: "outside-district-example@example.com",
    residentPhone: null,
    preferredLanguage: "English",
    contactConsent: true,
    newsletterOptIn: false,
    newsletterOptInAt: null,
    notificationReviewStatus: "ready",
    notificationReviewNote: "Ready for the outside-jurisdiction canned response.",
    notificationReviewedAt: "2026-05-18T16:35:53.929Z",
    assignedStaffId: null,
    createdAt: "2026-05-18T16:31:53.929Z",
    updatedAt: "2026-05-18T16:31:53.929Z",
  },
] as const;

export const DEMO_STATUS_EVENTS = [
  {
    id: "demo-status-sidewalks-received",
    reportId: "demo-report-sidewalks-miami",
    status: "received",
    publicNote: "Your report was received and is waiting for staff review.",
    createdAt: "2026-05-18T15:10:26.341Z",
  },
  {
    id: "demo-status-pothole-received",
    reportId: "demo-report-pothole-miami",
    status: "received",
    publicNote: "Your report was received and is waiting for staff review.",
    createdAt: "2026-05-18T16:00:37.848Z",
  },
  {
    id: "demo-status-pothole-routed",
    reportId: "demo-report-pothole-miami",
    status: "routed",
    publicNote:
      "District 7 staff routed this roadway issue for agency review and follow-up.",
    createdAt: "2026-05-18T16:24:30.938Z",
  },
  {
    id: "demo-status-parks-received",
    reportId: "demo-report-park-lighting",
    status: "received",
    publicNote: "Your report was received and is waiting for staff review.",
    createdAt: "2026-05-17T14:12:00.000Z",
  },
  {
    id: "demo-status-parks-awaiting",
    reportId: "demo-report-park-lighting",
    status: "awaiting_agency",
    publicNote:
      "District 7 staff is waiting on facility confirmation before sending a final update.",
    createdAt: "2026-05-17T15:05:00.000Z",
  },
  {
    id: "demo-status-outside-received",
    reportId: "demo-report-outside-district",
    status: "received",
    publicNote: "Sample outside-district report created for workflow testing.",
    createdAt: "2026-05-18T16:31:53.929Z",
  },
] as const;

export const DEMO_NOTES = [
  {
    id: "demo-note-pothole-1",
    reportId: "demo-report-pothole-miami",
    body: "Strong example of a case where Miami municipality + county transit parcel context helps narrow the follow-up path.",
    createdAt: "2026-05-18T16:18:00.000Z",
  },
  {
    id: "demo-note-parks-1",
    reportId: "demo-report-park-lighting",
    body: "Good demo case for showing how notification review can be set to hold pending ownership confirmation.",
    createdAt: "2026-05-17T14:40:00.000Z",
  },
] as const;

export const DEMO_REFERRALS = [
  {
    id: "demo-referral-pothole-1",
    reportId: "demo-report-pothole-miami",
    agencyName: "Public Works / roadway maintenance",
    referralMethod: "Email",
    outcomeStatus: "sent",
    externalReference: "D7-DEMO-ROAD-001",
    followUpDate: "2026-05-21",
    notes: "Demo referral for a roadway maintenance review near Douglas Road and US-1.",
    outcomeNote: null,
    createdAt: "2026-05-18T16:24:30.938Z",
    updatedAt: "2026-05-18T16:24:30.938Z",
  },
  {
    id: "demo-referral-parks-1",
    reportId: "demo-report-park-lighting",
    agencyName: "Parks department or facility operator",
    referralMethod: "Email",
    outcomeStatus: "acknowledged",
    externalReference: "D7-DEMO-PARK-002",
    followUpDate: "2026-05-20",
    notes: "Awaiting facility-side confirmation on the lighting asset owner.",
    outcomeNote: "Acknowledged by parks contact; staff requested a maintenance ETA.",
    createdAt: "2026-05-17T15:05:00.000Z",
    updatedAt: "2026-05-17T15:20:00.000Z",
  },
] as const;

export const DEMO_NOTIFICATION_EVENTS = [
  {
    id: "demo-notification-sidewalks-confirmation",
    reportId: "demo-report-sidewalks-miami",
    eventType: "confirmation",
    templateKey: "confirmation",
    recipient: "d48reu@gmail.com",
    subject: "District 7 received your report",
    body: "Thank you for reporting this issue to District 7. Staff will review the report and follow up through your tracking page.",
    deliveryStatus: "local_stub",
    createdAt: "2026-05-18T15:10:26.341Z",
  },
  {
    id: "demo-notification-pothole-confirmation",
    reportId: "demo-report-pothole-miami",
    eventType: "confirmation",
    templateKey: "confirmation",
    recipient: "d48reu@gmail.com",
    subject: "District 7 received your report",
    body: "Thank you for reporting this issue to District 7. Staff will review the report and follow up through your tracking page.",
    deliveryStatus: "local_stub",
    createdAt: "2026-05-18T16:00:37.848Z",
  },
  {
    id: "demo-notification-pothole-status",
    reportId: "demo-report-pothole-miami",
    eventType: "status_update",
    templateKey: "status_update",
    recipient: "d48reu@gmail.com",
    subject: "District 7 updated your report",
    body: "District 7 staff routed this roadway issue for agency review and follow-up.",
    deliveryStatus: "local_stub",
    createdAt: "2026-05-18T16:24:30.938Z",
  },
  {
    id: "demo-notification-parks-confirmation",
    reportId: "demo-report-park-lighting",
    eventType: "confirmation",
    templateKey: "confirmation",
    recipient: "parks-demo@example.com",
    subject: "District 7 received your report",
    body: "Thank you for reporting this issue to District 7. Staff will review the report and follow up through your tracking page.",
    deliveryStatus: "local_stub",
    createdAt: "2026-05-17T14:12:00.000Z",
  },
  {
    id: "demo-notification-outside-confirmation",
    reportId: "demo-report-outside-district",
    eventType: "confirmation",
    templateKey: "confirmation",
    recipient: "outside-district-example@example.com",
    subject: "District 7 received your report",
    body: "District 7 received your report. Staff will review the jurisdiction and route it as appropriate.",
    deliveryStatus: "local_stub",
    createdAt: "2026-05-18T16:31:53.929Z",
  },
] as const;
